Export hackathon tests
pressbooks/pressbooks pull request #2474
Opened 2021-10-29 18:30 UTC by richard015ar

Description TK

2021-10-29 19:01 UTC, richard015ar commented on inc/modules/export/xhtml/class-xhtml11.php
> +
It was a linting auto-fix. For some reason PHPCS complains about this.

2021-10-29 19:01 UTC, richard015ar commented on templates/export/generic-post-type.blade.php
> +		{!! $endnotes !!}
We can have footnotes and endnotes with paragraph, images, and other html elements.

2021-10-29 19:02 UTC, richard015ar commented on tests/test-modules-export-export.php
> -		$this->assertContains( '</h2></div><div class="ugc chapter-ugc"><h2 class="chapter-subtitle">Or, A Chapter to Test</h2>', $xhtml_content );
We check structure in blade template testing.

2021-11-01 14:04 UTC, fdalcin requested changes
Really like your approach to the new tests @richard015ar.

However, I'm noticing a couple of things: 
I think you've accidentally deleted `tests/data/log.csv`. I left a couple of comments for the tests that fail. 

We have a tests that fails for EPUB validation that because it's rendering the slug in a bad way. We can ignore this failing test for now because this is fixed in another branch and should be fine once both are merged.

2021-11-01 16:03 UTC, fdalcin approved these changes

2021-11-01 16:03 UTC, fdalcin approved these changes
LGMT, thanks @richard015ar

2021-11-01 16:03 UTC, merged