feat: Improve digital PDF a11y
pressbooks/pressbooks pull request #2532
Opened 2021-11-25 17:47 UTC by fdalcin

Fixes pressbooks/pressbooks#2300 and pressbooks/pressbooks#2485. Accompanies .

This PR does a couple of things:
1. It adds back the invisible `span` on PDFs because without them the Digital PDF version has empty bookmark if Show Title is set to `false`.
2. It adds a new `has-subsections` class to identify when 2-level TOC is enabled.
3. It creates a `part-wrapper` div around the whole part + chapters

#### How to test

See pressbooks/pressbooks#2485 for a clear understanding and make sure of the following:

- Half title page and title page are not visible in digital pdf bookmarks
- Table fo contents is a level 1 bookmark
- Each front/back matter is displayed as a level 1 bookmark
- If a book has more than 1 visible part, ensure that the title of each part is displayed as a level 1 bookmark
- Display the title of each chapter within a visible part as level 2 bookmark
- Display the title of each chapter within an invisible part as a level 1 bookmark
- If the two-level ToC enabled, all H1s inside of chapters within a visible part should be displayed with the corresponding bookmark level. Level 2 when chapter is a level 1, and level 3 when chapter is a level 2.

2021-11-25 18:15 UTC, fdalcin commented on inc/modules/export/class-exporthelpers.php
> +		}
Added this back because digital PDF bookmarks will display an empty bookmark if the H1 has no content.

2021-11-25 18:15 UTC, fdalcin commented on inc/modules/export/xhtml/class-xhtml11.php
> +			yield from $this->renderBackMatterGenerator( $book_contents, $metadata );
Renamed the method just for consistency.

2021-11-25 18:15 UTC, fdalcin commented on inc/modules/export/xhtml/class-xhtml11.php
> +				if ( $parse_subsections && \Pressbooks\Book::getSubsections( $chapter_id ) !== false ) {
Small improvement to avoid calling the same method for each chapter since this is an export option.

2021-11-25 18:15 UTC, fdalcin commented on inc/modules/export/xhtml/class-xhtml11.php
> +	}
New helper method to wrap the part + chapter content into a new `div`.

2021-11-25 18:15 UTC, fdalcin commented on templates/export/chapter.blade.php
> +<div class="chapter {{ $subclass }} {{ $subsection_class ?? '' }}" id="{{ $slug }}" title="{{ $sanitized_title }}">
New subsection class that helps to identify 2-level TOC.

2021-11-25 18:15 UTC, fdalcin commented on templates/export/chapter.blade.php
> +		<h1 class="chapter-title">{!! $title !!}</h1>
Chapter title should be an H1 instead of H2.

2021-11-25 23:57 UTC, arzola requested changes
Really nice job here @fdalcin I was reviewing the output of this and I'm not sure if it's needed or if I'm not understanding it very well but the H1 tags inside of any front/back matter are not being shown in the bookmark?

As you can see here the TOC shows the H1s
![image.png](https://images.zenhubusercontent.com/58e3ccc251aa2c30577a5c97/2182ac18-cc85-48db-8b2a-0810c16698b2)

But the bookmarks are not showing the nested H1 inside

![image.png](https://images.zenhubusercontent.com/58e3ccc251aa2c30577a5c97/dbbe6e38-9438-4899-8583-fb775a7d0157)

2021-11-26 00:10 UTC, fdalcin commented
@arzola I think that it should show bookmarks for all H1 inside front/back matters if 2-level TOC is enabled. I'm not handling this at the moment, will check it tomorrow. Thanks for reviewing it and catching this.

2021-11-26 14:34 UTC, arzola commented
@fdalcin excellent

2021-11-26 14:45 UTC, arzola approved these changes
LGTM

2021-11-26 15:11 UTC, merged