Replace intervention
pressbooks/pressbooks pull request #2748
Opened 2022-04-15 15:04 UTC by SteelWagstaff

This PR moves some of the functionality previously delegated to soberwp/intervention in pressbooks-book and aldine into core Pressbooks. It accompanies https://github.com/pressbooks/pressbooks-book/pull/1010 and https://github.com/pressbooks/pressbooks-aldine/pull/326

2022-04-15 19:10 UTC, greatislander approved these changes

2022-04-15 19:11 UTC, greatislander requested changes
I'd add some tests to ensure coverage doesn't slip.

2022-04-15 22:38 UTC, SteelWagstaff commented
@greatislander Added new tests and split CI pipeline into two separate steps as recommended.

2022-04-16 13:54 UTC, greatislander approved these changes

2022-04-17 00:49 UTC, merged