chore: apply changes for PHP 8 compat
pressbooks/pressbooks pull request #2975
Opened 2022-10-12 15:30 UTC by fdalcin

TK

2022-10-12 16:41 UTC, fdalcin commented on .github/workflows/standards-and-tests.yml
> +
I've updated the pipeline a bit so now it runs the following matrix

|. PHP | WP | experimental |
| :-: | :-: | :-: |
| 7.4 | 6.0.2 | true |
| 7.4 | latest | true |
| 8.0 | 6.0.2 | false |
| 8.0 | latest | true |

This results on 4 different jobs that will run tests, however only the PHP 8.0 + WP 6.0.2 will run the CS and Code coverage. In the future when we drop PHP 7.4 support we simply remove 7.4 from the test matrix and the pipeline should be ok.

2022-10-13 13:28 UTC, richard015ar approved these changes
I tested it locally and works without notice, errors or warnings in the debug and error logs.
Changes LGTM.
However, more manual testing is recommended.

2022-10-18 18:39 UTC, arzola requested changes
LGTM

Just we need to keep an eye on the `libxml_disable_entity_loader` removal because according to the docs on versions lower than PHP 8 using the following flag could lead to a security thread

![image](https://user-images.githubusercontent.com/4997549/196515721-e8377897-9c85-48d6-822f-acbfcc40f3dc.png)

https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation

So I suggest to add one of the following conditions with a TODO tag to remove when we get rid of PHP 7.4

```
if (\PHP_VERSION_ID < 80000) {
      libxml_disable_entity_loader(true);
 }
//or
if (\LIBXML_VERSION < 20900) {
      libxml_disable_entity_loader(true);
 }
```

2022-10-18 19:09 UTC, fdalcin commented
Thanks @arzola, I've addressed your suggestion

2022-10-18 19:32 UTC, merged