feat: replace custom-metadata-manager
pressbooks/pressbooks pull request #3502
Opened 2023-10-28 17:53 UTC by greatislander

2023-10-29 00:21 UTC, greatislander commented
PHP CodeSniffer appears to be failing because of this: https://github.com/squizlabs/PHP_CodeSniffer/issues/3641

It could be solved by upgrading to WordPress Coding Standards 3.x but Human Made Coding Standards is still locked to 2.3 🙈

2023-12-26 14:11 UTC, greatislander commented
Ready for review. Requires changes to Pressbooks BISAC as well (see: https://github.com/pressbooks/pressbooks-bisac/issues/46)

2023-12-26 18:43 UTC, greatislander commented
Requires these changes too: https://github.com/pressbooks/pressbooks-bisac/pull/47

2024-01-10 19:14 UTC, fdalcin requested changes
Hi @greatislander, thank you for your time working on this PR. I really like the new metabox approach.

While reviewing it we've detected a couple of minor issues where content was not being displayed properly, so I added some comments with suggestions.

We've also noticed a weird behaviour with the wysiwyg field. As you can see in the image below, when changing to **Text** mode the wysiwyg's layout renders weirdly. I'm not entirely sure about the cause, but am assuming some styling might have been removed by accident.

<img width="1792" alt="image" src="https://github.com/pressbooks/pressbooks/assets/1761690/0bdf0b6d-4fe8-4966-b46f-82e10da8ea14">

2024-01-10 19:14 UTC, fdalcin commented on templates/metaboxes/fields/wysiwyg.blade.php
> +	@php(wp_editor($value ?? '', $field->name, \Pressbooks\Editor\metadata_manager_default_editor_args(['textarea_rows' => $field->rows ?? 20])))
```suggestion
	@php(wp_editor($field->value ?? '', $field->name, \Pressbooks\Editor\metadata_manager_default_editor_args(['textarea_rows' => $field->rows ?? 20])))
```

2024-01-10 19:14 UTC, fdalcin commented on templates/metaboxes/fields/textarea.blade.php
> +	</textarea>
```suggestion
	<textarea
		id="{{ $field->id ?? $field->name }}"
		name="{{ $field->name }}"
		type="{{ $field->type ?? 'text' }}"
		@if($field->disabled) disabled @endif
		@if($field->readonly) readonly @endif
		@if(isset($field->description)) aria-describedby="{{ $field->id ?? $field->name . '-description' }}" @endif
	>{{ $field->value ?? '' }}</textarea>
```

2024-01-13 21:03 UTC, greatislander commented
@fdalcin Hi! I've addressed the issues, thanks for your review. Let me know if you encounter any other problems while testing.

2024-01-16 15:38 UTC, fdalcin commented
Hi @greatislander, I merged https://github.com/pressbooks/pressbooks/pull/3541 and now we have a couple of conflicts here. Would you mind resolving the conflicts before I can finish my review?

2024-01-16 18:43 UTC, fdalcin approved these changes
LGTM, tested locally and the issues were resolved. Thank you, @greatislander.

2024-01-16 19:31 UTC, arzola commented
LGTM

2024-01-16 19:32 UTC, merged